version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_dotnet_webapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GymPaymentDB;Trusted_Connection=false;User Id=sa;Password=Password1!;TrustServerCertificate=True;;
    ports:
      - "5000:80"
    command: ["sh", "-c", "dotnet ef database update && dotnet DockerGymApp.Service.dll"]

volumes:
  sql_data:
